#!/system/bin/sh
#Script for AOSPDesire

MODULES=/system/lib/modules/2.6.35.4-AOSPDesire

insmod $MODULES/kernel/fs/nfs_common/nfs_acl.ko;
insmod $MODULES/kernel/fs/nfs/nfs.ko;
insmod $MODULES/kernel/fs/exportfs/exportfs.ko;
insmod $MODULES/kernel/fs/nfsd/nfsd.ko;
insmod $MODULES/kernel/fs/lockd/lockd.ko;
insmod $MODULES/kernel/fs/cifs/cifs.ko;
insmod $MODULES/kernel/fs/fuse/fuse.ko;
insmod $MODULES/kernel/net/ipv6/ipv6.ko;
insmod $MODULES/kernel/net/ipv6/ah6.ko;
insmod $MODULES/kernel/net/ipv6/esp6.ko;
insmod $MODULES/kernel/net/ipv6/ipcomp6.ko;
insmod $MODULES/kernel/net/ipv6/xfrm6_tunnel.ko;
insmod $MODULES/kernel/net/ipv6/tunnel6.ko;
insmod $MODULES/kernel/net/ipv6/xfrm6_mode_transport.ko;
insmod $MODULES/kernel/net/ipv6/xfrm6_mode_tunnel.ko;
insmod $MODULES/kernel/net/ipv6/xfrm6_mode_beet.ko;
insmod $MODULES/kernel/net/ipv6/mip6.ko;
insmod $MODULES/kernel/net/ipv6/sit.ko;
insmod $MODULES/kernel/net/ipv6/ip6_tunnel.ko;
insmod $MODULES/kernel/net/sunrpc/sunrpc.ko;
insmod $MODULES/kernel/net/sunrpc/auth_gss/auth_rpcgss.ko;
insmod $MODULES/kernel/net/sunrpc/auth_gss/rpcsec_gss_krb5.ko;
