#!/system/bin/sh
#
# Common Loader Script write by meLIanTQ for AOSPDesire
# Common Loader: hosts / bootanimation.zip & recursive applications
# Push whats you want load here: SDCard/AOSPDesireLoader/LoadMe
# after perform a reboot (The LoadMe folder is delete after load)

echo "+++ Loading Common Loader Start";

echo "+++ Mounting /data & /sdcard as read-write";
busybox mount -o rw,nosuid,nodev,relatime -t yaffs2 /dev/block/mtdblock5 /data;
busybox mount -o rw,dirsync,nosuid,nodev,noexec,relatime,uid=1000,gid=1015 -t vfat /dev/block/mmcblk0p1 /sdcard
sleep 2

if [ ! -e "/sdcard/AOSPDesireLoader/LoadMe" ]; then

busybox echo "+++ Common Loader skipped, nothing to load";

else

busybox echo "+++ Copy hosts file if found";
busybox cp -f /sdcard/AOSPDesireLoader/LoadMe/hosts /data/local/hosts;
busybox echo "+++ Set permission of hosts file";
busybox chmod 644 /data/local/hosts;

busybox echo "+++ Copy bootanimation if found";
busybox cp -f /sdcard/AOSPDesireLoader/LoadMe/bootanimation.zip /data/local/bootanimation.zip;
busybox echo "+++ Set permission of bootanimation file";
busybox chmod 644 /data/local/bootanimation.zip;

busybox echo "+++ Install Applications on /data partition";
busybox chmod 777 /data/app;

for apk in /sdcard/AOSPDesireLoader/LoadMe/*.apk
do
busybox echo "+++ Install Application: $apk";
busybox cp -fp $apk /data/app
done

for apk in /data/app/*.apk
do
busybox echo "+++ Set permission of Applications: $apk";
busybox chmod 644 /data/app/*.apk
done

busybox echo "+++ Delete the LoadMe folder";
busybox rm -rf /sdcard/AOSPDesireLoader/LoadMe;

fi

echo "+++ Sync";
busybox sync;
sleep 2;

echo "+++ Unmounting SD Card";
busybox umount /sdcard;
sleep 2;

echo "+++ Loading Common Loader Stop";
