#!/system/bin/sh
# Script For AOSPDesire

####CPU Settings: Enable Safe Overclock for all Desire####

echo 245760 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1113600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

