#!/system/bin/sh
#
# Script for AOSPDesire

echo "+++ Loading hosts file Start";

echo "+++ Mounting /data & /sdcard as read-write";
busybox mount -o rw,nosuid,nodev,relatime -t yaffs2 /dev/block/mtdblock5 /data;
busybox mount -o rw,dirsync,nosuid,nodev,noexec,relatime,uid=1000,gid=1015 -t vfat /dev/block/mmcblk0p1 /sdcard
sleep 2

busybox echo "+++ Copy any hosts file found of the SDCard";
busybox cp -f /sdcard/hosts /data/local/hosts;
busybox echo "+++ Delete the hosts file of the SDCard";
busybox rm -f /sdcard/hosts;
busybox echo "+++ Set permission of hosts file";
busybox chmod 644 /data/local/hosts;

echo "+++ Sync";
busybox sync;
sleep 2;

echo "+++ Unmounting SD Card";
busybox umount /sdcard;
sleep 2;

echo "+++ Loading hosts file Stop";
